#links establish a link between two services so they are added to known host list
#depends_on is used to define in what order services must start and stop
#
version: '3'

services:
#  
  nginx:
    depends_on:
      - mariadb
    container_name: nginx
    image: nginx
    env_file: .env
    restart: unless-stopped
    build: ./requirements/nginx
    networks:
      - inception
    ports:
    - "443:443"
    volumes:
    - "wordpress:/var/www/wordpress"
  #
  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    restart: unless-stopped
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - "maria:/var/lib/mysql"
#    ports:
#    - "3306:3306"
  #
  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    env_file: .env
    restart: unless-stopped
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - "wordpress:/var/www/wordpress"
#    ports:
#    - "9000:9000"
#
networks:
  inception:
    driver: bridge
#
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ccottin/data/wordpress
  maria:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ccottin/data/mariadb
