#links establish a link between two services so they are added to known host list
#depends_on is used to define in what order services must start and stop
#
version: '3'

services:
  
  nginx:
    container_name: nginx
    env_file: .env
    restart: unless-stopped
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - "inception"
    volumes:
      - "/home/ccottin/data/wordpress:/var/www/html"
#
  mariadb:
    depends_on:
      - nginx
    container_name: mariadb
    env_file: .env
    restart: unless-stopped
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - "/home/ccottin/data/mariadb:/var/lib/mysql"
    networks:
      - inception

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    restart: unless-stopped
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - "/home/ccottin/data/wordpress:/var/www/html"
    networks:
      - inception
#
networks:
  inception:
    driver: bridge
